components:
  schemas:
    JsonSchema:
      type: object
      properties:
            Identificacao do Emitente:
                  type: object
                  properties:
                        Nome:
                              type: string
                        Morada:
                              type: string
                        NIF:
                              type: string
                        Contacto:
                              type: string
            Identificacao do Cliente:
                  type: object
                  properties:
                        Nome:
                              type: string
                        NIF:
                              type: string
                        Morada:
                              type: string
            Data e Hora da Factura:
                  type: object
                  properties:
                        Data:
                              type: string
                        Hora:
                              type: string
            Numero da Factura:
                  type: object
                  properties:
                        Factura-recibo:
                              type: string
                        Documentos referenciados:
                              type: string
            Valor Total:
                  type: string
                  description: Exemplo "KZ 500,00"
            IVA e Base Tributavel:
                  type: object
                  properties:
                        Base tributavel:
                              type: string
                        IVA (%):
                              type: string
                        Valor Total com IVA:
                              type: string
            Pagamento:
                  type: object
                  properties:
                        Forma de pagamento:
                              type: string
                        Valor:
                              type: string
            Outras Informacoes:
                  type: object
                  properties:
                        Software:
                              type: string
                        Emp.:
                              type: string
                        Data de processamento:
                              type: string

    UserRole:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ErrorMessage:
      type: object
      properties:
        error:
          type: string

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        name:
          type: string
          nullable: true
        image:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        password:
          type: string
        roleId:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        role:
          $ref: '#/components/schemas/UserRole'

    Category:
      type: object
      properties:
        id:
          type: string
          format: uuid
        icon:
          type: string
        colorHex:
          type: string
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        deletedAt:
          type: string
          format: date-time
          nullable: true
        deleted:
          type: boolean
        deletedBy:
          type: string
          nullable: true

    Type:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string

    Invoice:
      type: object
      properties:
        id:
          type: string
          format: uuid
        text:
          type: string
        jsonData:
          type: object  # Pode especificar o schema do JSON se quiser
          $ref: '#/components/schemas/JsonSchema'
        userId:
          type: string
        createdAt:
          type: string
          format: date-time
        categoryId:
          type: string
        typeId:
          type: string
        category:
          $ref: '#/components/schemas/Category'
        type:
          $ref: '#/components/schemas/Type'

    Plan:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        price:
          type: number
        currency:
          type: string
        invoiceLimit:
          type: integer
        features:
          type: object  # JSON
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Subscription:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
        planId:
          type: string
        status:
          type: string
          enum: [ACTIVE, PENDING, CANCELED, EXPIRED]
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
          nullable: true
        renewsAt:
          type: string
          format: date-time
          nullable: true
        canceledAt:
          type: string
          format: date-time
          nullable: true
        paymentMethod:
          type: string
          nullable: true
        externalRef:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

        